# Generated by Django 5.2.9 on 2026-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='video_length',
            field=models.CharField(),
        ),
    ]
